import pygsheets

# Linking service account
gc = pygsheets.authorize(service_account_file="testask-383916-7365cb3f27e9.json")

# Opening spreadsheet.
sh_pyg = gc.open("work_table")

#  We are getting worksheet using gspread and saving as pandas dataframe
wks_users = sh_pyg[0]
users = wks_users.get_as_df()

# We need to get score table via gspread and save as pandas dataframe
wks_scores = sh_pyg[1]
scores = wks_scores.get_as_df()

# For correct output we need to sort table
# 1. Sorting by total number of reasons and statements. Creating new column with sum of two.
scores["total"] = scores[["total_statements", "total_reasons"]].sum(axis=1)

# For sorting in alphabet order we need to get all characters in same case.
# Using upper case because it's more convenient for us.
scores["name_lowercase"] = scores["name"].str.upper()
scores = scores.sort_values(by=["total", "name_lowercase"], ascending=[False, True])

# Deleting helping rows after sorting + deleting number since we won't need old order
del scores["name_lowercase"]
del scores["total"]
del scores["S No"]

# Adding new column with autogenerated rank
scores.insert(0, "Rank", range(1, 1+len(scores)))
print(scores)

out_pyg_2 = sh_pyg[2]
out_pyg_2.set_dataframe(scores, (1,1))
